#端口号
server:
  port: 8501

#服务名
spring:
  application:
    name: kst-auth
  # 环境设置：dev、test、prod
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/xzs?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '000923'
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #nacos配置
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8858

  # redis 配置
  redis:
    # 地址
    host: localhost
    # 端口，默认为6379
    port: 6379
    # 数据库索引
    database: 0
    # 密码
    password:
    # 连接超时时间
    timeout: 10s
    lettuce:
      pool:
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池的最大数据库连接数
        max-active: 8
        # #连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms


logging:
  level:
    com.baomidou.mybatisplus.samples.quickstart: debug
#    org.springframework: debug
mybatis-plus:
  # mybatis-plus配置
  mapper-locations: classpath:mapper/*Mapper.xml
  configuration:
    # 输出到控制台
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#ribbon的超时时间
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000